# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{arcserver.rb}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin Casey"]
  s.date = %q{2009-10-13}
  s.email = %q{casey.colin@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "arcserver.rb.gemspec",
     "lib/arcserver.rb",
     "lib/arcserver/map_server.rb",
     "lib/arcserver/rest/map_server.rb",
     "lib/arcserver/soap/map_server.rb",
     "lib/arcserver/url_helper.rb",
     "test/functional/soap/map_server_test.rb",
     "test/test_helper.rb",
     "test/unit/map_server_test.rb",
     "test/unit/url_helper_test.rb"
  ]
  s.homepage = %q{http://github.com/colincasey/arcserver.rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Library for accessing ESRI ArcServer REST and SOAP APIs.}
  s.test_files = [
    "test/test_helper.rb",
     "test/functional/soap/map_server_test.rb",
     "test/unit/url_helper_test.rb",
     "test/unit/map_server_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.4.5"])
      s.add_runtime_dependency(%q<handsoap>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_runtime_dependency(%q<httpclient>, [">= 2.1.5"])
      s.add_development_dependency(%q<jeweler>, [">= 1.2.1"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.2"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
    else
      s.add_dependency(%q<httparty>, [">= 0.4.5"])
      s.add_dependency(%q<handsoap>, [">= 1.1.0"])
      s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_dependency(%q<httpclient>, [">= 2.1.5"])
      s.add_dependency(%q<jeweler>, [">= 1.2.1"])
      s.add_dependency(%q<shoulda>, [">= 2.10.2"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.4.5"])
    s.add_dependency(%q<handsoap>, [">= 1.1.0"])
    s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
    s.add_dependency(%q<httpclient>, [">= 2.1.5"])
    s.add_dependency(%q<jeweler>, [">= 1.2.1"])
    s.add_dependency(%q<shoulda>, [">= 2.10.2"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
  end
end
